import { BeerType, Breed, Cow, GrassPreference } from "../shared/types";

export const specialHerd: Cow[] = [
    {
        name: "Bartholomoo",
        age: 4,
        weightInKg: 720,
        heightInMeters: 1.6,
        grassPreference: GrassPreference.DeepGreen,
        breed: Breed.HolsteinFriesian,
        favoriteBeer: BeerType.OatmealStout,
        isReligious: true,
        image: "https://cdn.britannica.com/55/174255-050-526314B6/brown-Guernsey-cow.jpg",
        funFact: "Writes radical bovine theology in the mud."
    },
    {
        name: "Daisy 'The Hulk'",
        age: 6,
        weightInKg: 1150,
        heightInMeters: 1.8,
        grassPreference: GrassPreference.ExtraTall,
        breed: Breed.BelgianBlue,
        favoriteBeer: BeerType.IndiaPaleAle,
        isReligious: false,
        image: "https://media.4-paws.org/c/b/4/0/cb40fd6eba56c2ab90bba9cfb5f0de4fe4014349/VIER%20PFOTEN_2015-04-27_010-3369x2246-3246x2246.jpg",
        funFact: "Can bench press a small John Deere tractor."
    },
    {
        name: "Soy-Boy",
        age: 2,
        weightInKg: 450,
        heightInMeters: 1.2,
        grassPreference: GrassPreference.SoyGrass,
        breed: Breed.SimmentalCattle,
        favoriteBeer: BeerType.LowCarb,
        isReligious: false,
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Cow_female_black_white.jpg",
        funFact: "A modern, tech-focused cow who prefers podcasts to mooing."
    },
    {
        name: "Old Rusty",
        age: 12,
        weightInKg: 890,
        heightInMeters: 1.5,
        grassPreference: GrassPreference.RottenBrown,
        breed: Breed.HerefordCattle,
        favoriteBeer: BeerType.RedLager,
        isReligious: true,
        image: "https://cdn.sanity.io/images/5dqbssss/production-v3/a25daafbd63d028bacd81f322618de5ea1b9bc98-6720x4480.jpg?w=3840&q=75&fit=clip&auto=format",
        funFact: "Claims he saw a UFO in 2022 and hasn't been the same since."
    },
    {
        name: "Sir Hops-a-Lot",
        age: 5,
        weightInKg: 780,
        heightInMeters: 1.6,
        grassPreference: GrassPreference.DeepGreen,
        breed: Breed.AberdeenAngus,
        favoriteBeer: BeerType.IndiaPaleAle,
        isReligious: false,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgiEvY2QXXK2t_9rWu3uDF25nDLQVFAXALrw&s",
        funFact: "The reigning local champion at hoof-pong."
    },
    {
        name: "Sister Mary Moo",
        age: 8,
        weightInKg: 650,
        heightInMeters: 1.4,
        grassPreference: GrassPreference.DeepGreen,
        breed: Breed.LimousinCattle,
        favoriteBeer: BeerType.CreamAle,
        isReligious: true,
        image: "https://www.shutterstock.com/image-photo/dairy-cows-feeding-fields-cattle-600nw-2654428055.jpg",
        funFact: "Strictly refuses to graze on Sundays; spends the day staring at the sun."
    },
    {
        name: "Zen Master Zen",
        age: 10,
        weightInKg: 900,
        heightInMeters: 1.7,
        grassPreference: GrassPreference.ExtraTall,
        breed: Breed.HolsteinFriesian,
        favoriteBeer: BeerType.OatmealStout,
        isReligious: true,
        image: "https://www.drink-milk.com/wp-content/uploads/2019/09/Ayrshire-950x650.png",
        funFact: "Has achieved total inner peace and can sleep standing on one hoof."
    },
    {
        name: "Lager Larry",
        age: 3,
        weightInKg: 820,
        heightInMeters: 1.5,
        grassPreference: GrassPreference.SoyGrass,
        breed: Breed.HerefordCattle,
        favoriteBeer: BeerType.RedLager,
        isReligious: false,
        image: "https://t3.ftcdn.net/jpg/06/79/87/24/360_F_679872467_BlgAxGs59mThCSmKU00WUZ34y7HhRvJ0.jpg",
        funFact: "Only grazes during Happy Hour (4 PM to 6 PM)."
    },
    {
        name: "Princess Beef",
        age: 4,
        weightInKg: 710,
        heightInMeters: 1.6,
        grassPreference: GrassPreference.DeepGreen,
        breed: Breed.BelgianBlue,
        favoriteBeer: BeerType.CreamAle,
        isReligious: false,
        image: "https://lait.org/app/uploads/2024/09/la-vache-ayrshire-1536x966.jpg",
        funFact: "Won 'Miss Pasture' three years running; very high maintenance."
    },
    {
        name: "Gloom-Hoof",
        age: 7,
        weightInKg: 840,
        heightInMeters: 1.5,
        grassPreference: GrassPreference.RottenBrown,
        breed: Breed.AberdeenAngus,
        favoriteBeer: BeerType.OatmealStout,
        isReligious: true,
        image: "https://dc-peakdistrict.transforms.svdcdn.com/production/assets/images/Main%20Images/Highland-Cows-of-the-Peak-baby-cow.jpg?w=640&h=320&q=90&auto=format&fit=crop&dm=1750430375&s=04cf698318c20fed7d58c5dd49b12c23",
        funFact: "Only listens to existential jazz and heavy rain sounds."
    },
    {
        name: "Turbo",
        age: 2,
        weightInKg: 500,
        heightInMeters: 1.3,
        grassPreference: GrassPreference.ExtraTall,
        breed: Breed.SimmentalCattle,
        favoriteBeer: BeerType.LowCarb,
        isReligious: false,
        image: "https://www.highlandtitles.com/wp-content/uploads/2019/11/Cow_on_Pupers.jpg",
        funFact: "Exceptionally fast; once outran a border collie for a dare."
    },
    {
        name: "The Prophet",
        age: 15,
        weightInKg: 950,
        heightInMeters: 1.6,
        grassPreference: GrassPreference.DeepGreen,
        breed: Breed.LimousinCattle,
        favoriteBeer: BeerType.RedLager,
        isReligious: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt0kImHRk20GbUXOQlrFHyBlgE1VCbFwUEwg&s",
        funFact: "Predicts the exact minute it will start raining with 99% accuracy."
    },
    {
        name: "IPA-Bella",
        age: 5,
        weightInKg: 730,
        heightInMeters: 1.5,
        grassPreference: GrassPreference.SoyGrass,
        breed: Breed.HolsteinFriesian,
        favoriteBeer: BeerType.IndiaPaleAle,
        isReligious: false,
        image: "https://ichef.bbci.co.uk/ace/standard/3840/cpsprodpb/c7c7/live/2e431eb0-0261-11f1-b5e2-dd58fc65f0f6.jpg",
        funFact: "A craft beer connoisseur who can taste notes of citrus in her grass."
    },
    {
        name: "Stout Sam",
        age: 9,
        weightInKg: 1050,
        heightInMeters: 1.7,
        grassPreference: GrassPreference.RottenBrown,
        breed: Breed.AberdeenAngus,
        favoriteBeer: BeerType.OatmealStout,
        isReligious: false,
        image: "https://static.scientificamerican.com/sciam/cache/file/D2CC97C1-2D8E-428E-94F4F658E7B49E89_source.jpeg?crop=4%3A3%2Csmart&w=1200",
        funFact: "Legend says he can drink three pails of stout and still walk a straight line."
    },
    {
        name: "Grace",
        age: 6,
        weightInKg: 680,
        heightInMeters: 1.4,
        grassPreference: GrassPreference.DeepGreen,
        breed: Breed.HerefordCattle,
        favoriteBeer: BeerType.CreamAle,
        isReligious: true,
        image: "https://opensanctuary.org/wp-content/uploads/2025/03/WAM42436-scaled.jpg",
        funFact: "Known for her exceptionally polite, melodic 'Moo'."
    },
    {
        name: "Bluey",
        age: 4,
        weightInKg: 1200,
        heightInMeters: 1.8,
        grassPreference: GrassPreference.ExtraTall,
        breed: Breed.BelgianBlue,
        favoriteBeer: BeerType.LowCarb,
        isReligious: false,
        image: "https://images.twinkl.co.uk/tw1n/image/private/t_630_eco/website/uploaded/cow-6360406-1280-1729765657.jpg",
        funFact: "Is currently trying to cut back on carbs for the summer season."
    },
    {
        name: "Meadow",
        age: 3,
        weightInKg: 590,
        heightInMeters: 1.3,
        grassPreference: GrassPreference.SoyGrass,
        breed: Breed.LimousinCattle,
        favoriteBeer: BeerType.CreamAle,
        isReligious: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbNlIzdPrUjXo-5PJmZoaOlg44Uu8l7HHDaw&s",
        funFact: "Believes every blade of grass has its own tiny soul."
    },
    {
        name: "Angus Young",
        age: 5,
        weightInKg: 810,
        heightInMeters: 1.5,
        grassPreference: GrassPreference.DeepGreen,
        breed: Breed.AberdeenAngus,
        favoriteBeer: BeerType.RedLager,
        isReligious: false,
        image: "https://res.cloudinary.com/dotcom-prod/images/c_fill,f_auto,g_faces:center,q_auto,w_1920/v1/wt-cms-assets/2026/01/w5suuo1u6crewjgru7ic/oreocowshero.jpg",
        funFact: "Plays a mean air-guitar with its tail when the wind is right."
    },
    {
        name: "Rowdy Roddy",
        age: 7,
        weightInKg: 880,
        heightInMeters: 1.6,
        grassPreference: GrassPreference.ExtraTall,
        breed: Breed.SimmentalCattle,
        favoriteBeer: BeerType.IndiaPaleAle,
        isReligious: false,
        image: "https://www.dairyglobal.net/app/uploads/2021/09/001_931_IMG_DAG_16_WEB_2BreedingsaferhornlessHolsteincows_credit.jpg",
        funFact: "Banned from three different barns for excessive partying."
    },
    {
        name: "Final Boss",
        age: 11,
        weightInKg: 1300,
        heightInMeters: 1.9,
        grassPreference: GrassPreference.RottenBrown,
        breed: Breed.BelgianBlue,
        favoriteBeer: BeerType.OatmealStout,
        isReligious: true,
        image: "https://cdn.britannica.com/22/522-050-25222A61/Jersey-cow.jpg",
        funFact: "The undisputed leader. Even the farmer asks him for permission."
    }
];